### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by inxomnyaa** [inxomnyaa/MagicWE#10]
- [x] progress updates on async actions
- [x] more brushes
- [x] translations
- [x] more translation keys
- [x] rewrite async a little
- [x] undo redo
- [x] probably fix flip
- [x] Rotate
- [x] session saving/loading to/from file
- [ ] Stack
- [ ] Move
- [x] Brush nameable
- [ ] Tile/Entity setting/fixing/copying
- [ ] Border
- [x] Add back `//brush` and `//flood`

**Comment by optimusprime338** [comment]
@thebigsmileXD Add //undo please.

**Comment by thebigsmileXD** [comment]
- [ ] Stack
- [ ] Move
- [ ] Brush nameable
- [ ] Tile/Entity setting/fixing/copying

**Comment by shdudwns** [comment]
is it project dead?

**Comment by Aericio** [comment]
@shdudwns basically. no new features will be added.

**Comment by Aericio** [comment]
https://github.com/pmmp/PocketMine-MP/pull/2308

New FormAPI pull request to PMMP. `//brush` and `//flood` may be reenabled again, if accepted and if commands actually work.

**Comment by naja82** [comment]
When we can use async commands, When I fill 4.1Million blocks it takes 180 seconds for respond on Server Thread please add async workers as soon as possible

**Comment by inxomnyaa** [comment]
Updated the issue based on the async branch

**Comment by Aericio** [comment]
PHPStan Level 8 is next.

**Comment by inxomnyaa** [comment]
I will actually delay PHPStan Level 8 (only null type checks), it is pretty annoying and "useless" (i already fixed real/major issues)

Currently i am working on //rotate and //flip, rotate comes first because it is easier to swap the states

You can take a look at the https://github.com/thebigsmileXD/MagicWE2/tree/feature-flip-rotate branch, but it is not yet functional. But i am doing great progress so far!

**Comment by inxomnyaa** [comment]
Closing as separate issues exist
Stack / Move / Expand: #21 #187
BlockEntities / Entity copying: #215
Border: Will be added after flags rework

**Comment by System0x20** [comment]
That's unfortunate. MagicWE2 was a handy plugin. Thank you @thebigsmileXD. R.I.P MagicWE2
